---@class Rabbit.Message.Preview: Rabbit.Message
---@field type "preview"
---@field file? string File to preview (only necessary if bufid is nil)
---@field bufid? integer Buffer number to preview
---@field linenr? integer Line number to preview
---@field winid? integer Window number to preview
---@field col_start? integer Column number to highlight (if nil, entire line is highlighted)
---@field col_end? integer Column number to highlight (if nil, entire line is highlighted)
