---@class Rabbit.Message.Rename: Rabbit.Message
---@field type "rename"
---@field apply fun(entry: Rabbit.Entry, new_name: string): string Returns the corrected name, but also immediately applies the change to the entry object.
---@field check fun(entry: Rabbit.Entry, new_name: string): string Returns the corrected name. Does not apply the change yet
---@field name string Existing name of the entry.
---@field color fun(entry: Rabbit.Entry, new_color: string) | false Sets the color of the entry
